### PR TITLE
bounce tests for d2q9_kuper

### PR DESCRIPTION
**Pull request by mdzik**
I added first tests for current version of d2q9_kuper + python integration.
To comply with #63

### CODE REVIEW

**Comment by mdzik** [comment]
On my machine seems OK.

Running "drop" test... OK (6.00s)
 > Checking ./output/drop_VTK_P00_00000050.vti.sha1... OK (SHA1 checksum)
 > Checking ./output/drop_VTK_P00_00000030.vti.sha1... OK (SHA1 checksum)
 > Checking ./output/drop_VTK_P00_00000010.vti.sha1... OK (SHA1 checksum)
 > Checking ./output/drop_VTK_P00_00000040.pvti... OK 
 > Checking ./output/drop_VTK_P00_00000050.pvti... OK 
 > Checking ./output/drop_VTK_P00_00000030.pvti... OK 
 > Checking ./output/drop_VTK_P00_00000010.pvti... OK 
 > Checking ./output/drop_sumF.csv... OK (csvdiff)
 > Checking ./output/drop_VTK_P00_00000020.pvti... OK 
 > Checking ./output/drop_VTK_P00_00000020.vti.sha1... OK (SHA1 checksum)
 > Checking ./output/drop_VTK_P00_00000040.vti.sha1... OK (SHA1 checksum)

Could someone run it and post me all output and the naughty one: ./output/drop_sumF.csv ?

**Comment by llaniewski** [comment]
@mdzik remember that Travis-CI runs the CPU version for tests.

**Comment by mdzik** [comment]
@llaniewski Yep. Could you run it for me? Or maybe there is a way to run in "interactively" on travis?

**Comment by mdzik** [comment]
I found a way to do it locally on TravisCi machine, it's quite easy. I'll make some wiki/script when I'm done :)

**Comment by mdzik** [comment]
I hope it will work.

There is a ~E-15 difference with my version of python and the one on TravisCi, for average and sum calculations :/
There is a "standard" python version with tool kits: Anaconda. We should switch to that, so one could make test on single machine and match with TravisCi. On me ;)

**Pull request merged**
