### PR TITLE
Adding proper Symmetry BC

### PR DESCRIPTION
**Pull request by shkodm**
I added properly working template for symmetry boundary condition. 
First argument is direction of symmetry, second - sign of vector; similarly to ZouHe. 

Example: 
```cuda
CudaDeviceFunction void BottomSymmetry() {
<?R SymmetryNew(2, 1) ?>
}

### CODE REVIEW

**Comment by mdzik** [comment]
OK, so if old one is "non properly" working, pleas remove it, rename SymmetryNew to Symmetry and replace in requiring models

**Comment by mdzik** [comment]
And one general comment: **pleas do not pull/merge XXX_new's**, its either something different and have different name or should replace XXX in all codebase. What would you do, when you decide to improve XXX_new? it will be XXX_new_new or XXX_verynew?

In case of models: new implementation starts its life in experimental/ then replace in stable/

**Comment by shkodm** [comment]
@mdzik, that is really good idea. For ZouHe, we already have ZouHe, ZouHeNew and ZouHeRewrite...

**Comment by mdzik** [comment]
Pull request #62

**Pull request merged**
