### PR TITLE
Conditional container. Evaluate actions inside ONLY if

### PR DESCRIPTION
**Pull request by mdzik**
if (Model compilation option is present and listed in "opt_present")
elseif ( "opt_missing" is used, and listed compilation option is missing not present)

Example:

XML
```xml
<EvalIf opt_present="bc">
<CallPython module="zalesak" function="setSwirl" densities="BC[0],BC[1]" pythonpath="./example/multiphase/csf"/> 
 </EvalIf>
```

model/.../conf.R
```R
OPT="bc"
```
Dynamics.R
```R
if (Options$BC) {
	AddDensity( name="BC[0]", group="BC", parameter=TRUE)
	AddDensity( name="BC[1]", group="BC", parameter=TRUE)
}
```

CallPYthon evaluated:
```bash
make d2q9_bc
mpirun CLB/d2q9_bc/main xxxxx
```

CallPython not evaluated:
```bash
make d2q9
mpirun CLB/d2q9/main xxxxx
```

### CODE REVIEW

**Comment by llaniewski** [comment]
I think `<If ...>` would be better.
Please add the element to the doc/elements.yaml so the documentation will be generated for it.

**Comment by mdzik** [comment]
We might need another If or have some conflict with xslt, pre/post
processing tools etc (if usqr < eps then change solver/turn something on).
plain "if" might be dangerous, are you brave enough? :)

2018-06-29 16:17 GMT+02:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
This should help:
https://github.com/CFD-GO/TCLB/blob/6d85f9f41d9d805f2ca05b5cfb1d1b6c19bbbc98/.travis.yml#L76

**Comment by llaniewski** [comment]
Oh. sorry. It's for v6.2_candidate. Maybe this could be migrated there? We'll soon merge.

**Comment by llaniewski** [comment]
@mdzik v6.2_candidate was merged to develop (#183 ), so add to elements.yaml and check.

**Comment by mdzik** [comment]
Ok, monday ;)

2018-08-16 15:48 GMT+02:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by mdzik** [comment]
Depends on #217

**Pull request merged**
