### PR TITLE
Adding support for "drawing" mode in Geometry

### PR DESCRIPTION
**Pull request by llaniewski**
I added the feature in the Geometry module, that allows to specify if a node should be:
- `mode="overwrite"` -- Overwrites the previous value of the node type
- `mode="change"` -- Overwrites only non-zero node types.
- `mode="fill"` -- Sets the node type only in elements that didn't have the node type earlier (had 0 in this `mask`)

Example:
```xml
<EVelocity mode="fill">
```
will set the EVelocity boundary condition only on elements that don't have previously set boundary condition.

@mdzik @shkodm

### CODE REVIEW

**Comment by mdzik** [comment]
What about zones? They go by the same rule?

**Comment by llaniewski** [comment]
@mdzik The rule applies to all things covered by the "mask". So for instance `<EVelocity mode="fill" name="Inlet">` will not modify elements that have a zone name already set.

I was considering adding an additional mask for the `mode` feature, but I didn't want to overcomplicate it.

**Comment by llaniewski** [comment]
I fixed the merge conflict. @mdzik I will merge after the test success. We can modify the behaviour later if we have better ideas how it should work.

@mdzik @shkodm The default `mode` is "overwrite" so if you don't specify it, it will work as earlier.

**Comment by mdzik** [comment]
OK.
So if I have <None name="test"> overlapped  by <EVelocity name="test2"> then ??
Maybe picture in wiki?
This behaviour need to be clearified

**Pull request merged**
