### PR TITLE
Clean d2q9s

### PR DESCRIPTION
**Pull request by mdzik**
Refactorized d2q9s models: d2q9, d2q9_kuper, d2q9_pf d2q9_csf
Upgraded python integration and unit tests

### CODE REVIEW

**Comment by llaniewski** [comment]
So this makes the python integration work?

**Comment by mdzik** [comment]
Hope so :)
All futures are tested, and I use it for month without errors

2016-10-28 10:49 GMT+02:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
Oi, mate! You broke d2q9.

I cannot allow it! Even example/karman.xml doesn't work! It's over complicated - d2q9 should be the simple one!

**Comment by mdzik** [comment]
It probably doesn't  work because of the name changes. Will check. (And
karman is not the unit test :p)
Maybe d2q9_simple? We need place to test/add new futures like python, bc
etc/

2016-10-28 16:15 GMT+02:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
@mdzik  lot of things happening here. Ready to go?

**Comment by mdzik** [comment]
So:
- it should provide stable python integration
- I will provide simplified d2q9 soon

I think this should be merged, it's as stable as I could be without wider beta testing ;) And i will wait for feature requests/bugfixes

Sorry for delay -  project meeting :/

**Comment by llaniewski** [comment]
Can you merge (or rebase), with:
https://github.com/llaniewski/TCLB/commit/c47eade57393f3bff5e0330fbd68f87c55a42ac1

So we will have a common trunk.

Then there will be less fuzz downstream.

**Comment by mdzik** [comment]
done: #110

2016-12-04 20:39 GMT+01:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
Ok, I did the merge myself. Otherwise we would have a mess.

I will merge this if you do not have nothing more to do here. I will address the d2q9 simpleness later :D

**Comment by mdzik** [comment]
CSF is in a lot of senses a work in progress, but I would say go and deal
with bugfixes later ;)
Python is definitely RC 1


2016-12-05 18:08 GMT+01:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
Changed base to V6.1 RC. Merging.

**Pull request merged**
