### PR TITLE
Addition of TravisMitchell's (in progress) models (and first attempt at a pull request :s)

### PR DESCRIPTION
**Pull request by TravisMitchell**
I added models:
- d2q9_pp_MCMP (in progress)
- d2q9_pp_LBL      (in progress)
- d2q9_SRT           (single relaxation time tutorial file)
- wave                    (finite difference tutorial)

I added example files for models:
- For MCMP:
            - d2q9_pp_MCMP_test-00, d2q9_pp_MCMP_test-01-contact, 
- For LBL:
            - d2q9_pp_LBL_test00-drop
- For SRT tutorial:
            - d2q9_SRT_example
- For wave tutorial:
            - example/example.xml

I modified lib/boundary.R so that density groups not labelled "f" can be generated

### CODE REVIEW

**Comment by mdzik** [comment]
Nice :+1: 

Pleas remove file/lines that should not be there, like pngs, some python files to generate cases etc. Also remove your commented out inserts to wave, if they are not necessary

**Comment by TravisMitchell** [comment]
Will do, sorry I had thought initially I would be able to choose which files to add into the pull request. But I unfortunately seem to have found that it treats the fork as a changeset, so won't let me be selective with things I've committed in my repository.

I have removed the png file and the python files to generate cases, so hopefully this cleans it up a bit. I believe the remaining are model and example files, but I can also remove the ones that were created from the wiki tutorials if you prefer?

**Comment by shkodm** [comment]
It lets you keep files, if they are on another branch. So probably you can create a separate branch on your fork for storing all these additional files. Then, during pull request, only main repository "develop"  and your "develop" branch will be compared, and the rest will be ignored.

**Comment by mdzik** [comment]
Looks ok now.


To avoid "unwanted files" in pull request always start work form syncing develop, then make branch (git checkout -b feature/something), push it, and make pull request from it. 
You could put different new things in different branches, and fix them separately.
After pull request got accepted, you could drop branch, and resync develop from upstream.


Google git workflow , or git flow to some nice pictures and ideas how to use make fun with git ;)

**Comment by TravisMitchell** [comment]
I see, that makes sense - sorry I should have had a bit of a google for best practice in pull requests. Thank you for the info on it, I will keep this in mind for future pull requests :). 

Are we happy to have the completed tutorial files (wave finite difference and single relaxation time LBM) in the repository or would you rather I remove these from the pull request?

**Comment by mdzik** [comment]
Examples/tutorial files or OK. You could update wiki to reference them

**Comment by llaniewski** [comment]
@mdzik @TravisMitchell All finished?
I say: merge.

**Comment by mdzik** [comment]
:+1:

**Pull request merged**
