### PR TITLE
extending pythoncall features :)

### PR DESCRIPTION
**Pull request by mdzik**
extending to multiple Densities support, only that makes sense :)
fixing PYTHONPATH to support any external library, like mpi4py

it *should* be possible to write native C extensions, wrapped to CLB via python using blitz

and now you could call TCLB "The Monster" ;)

### CODE REVIEW

**Comment by llaniewski** [comment]
I'll keep this open until you're finished :-)

**Comment by mdzik** [comment]
ok, but i think i'm out of ideas for now :-)

**Comment by mdzik** [comment]
...something is definetly wrong with commits/merges...

**Comment by llaniewski** [comment]
pushing to TCLB is like catching a riding train :-) tedious, but fun.

**Comment by llaniewski** [comment]
If you want to push a commit, without running tests on travis, add [ci skip] to commit message

**Comment by mdzik** [comment]
Now I know, but this should compile. After all this conflicts :p

**Comment by mdzik** [comment]
outdated

**Pull request closed without merging**
