### PR TITLE
+ Issue with d2q9_pf_velocity clean up and fix + example

### PR DESCRIPTION
**Pull request by TravisMitchell**
+ General tidy up of the model and addition of options feature to allow for various collision operators without any extra code compilation. 

+ Added fixedIterator, needs to be greater than 1 for dynamic cases particularly if continuous phase is gas

+ Double checked grad and laplace operators and chemical potential calculations

+ Added droplet falling example that was where issues were noted.

### CODE REVIEW

**Comment by llaniewski** [comment]
@TravisMitchell does this fix the main issue in #252? Is the new model in agreement with your old published one?

**Comment by ggruszczynski** [comment]
@TravisMitchell @llaniewski  what are the conclusions regarding #252  ?

**Comment by TravisMitchell** [comment]
@ggruszczynski the result of the updated code now matches the original one that I wrote, and stably simulates the droplet falling test case that I was looking at with MRT and CM. The result is close, but does not match exactly with the pressure evolution model from Fakhari, Lee and Geier that I coded up. However, this seems to be from the model itself rather than alterations made to the code, as such I pushed the changes made above. We also found a bit of strange behaviour based on the initial location of the droplet, which may be an artefact of the central isotropic difference - but this requires further examination.
Current-status

**Comment by llaniewski** [comment]
@ggruszczynski @TravisMitchell I understand this matches now the previously published model and I'm merging this PR.

**Comment by ggruszczynski** [comment]
@TravisMitchell @llaniewski 
As you indicated, the `fixedIterator=2` has an influence on the results what was not noticed in the benchmarks used in the publication:
```
The equation for Fµ is implicit, because the N matrix depends on u, which depends on F. How-
ever, it has been found that there is no need to apply a sub-iteration routine to determine the
velocity more precisely because it does not affect the results. 
```

**Comment by ggruszczynski** [comment]
I have checked the previous release against new (merged) PR, the results are OK :)

**Pull request merged**
