### PR TITLE
D2q9 pf cm [rerun]

### PR DESCRIPTION
**Pull request by llaniewski**
A rerun of #194 (this time with the right branch for merge)
@TravisMitchell If you accept please accept the review in the github interface.
@ggruszczynski Check if everything is in order (I think I selected the right branch) and accept the review.

Old text:
Cascaded (CLBM) collision scheme is introduced for both hydrodynamics and phase-field.
Based on the d2q9_pf_velocity implemented by @TravisMitchell

### CODE REVIEW

**Comment by llaniewski** [comment]
@ggruszczynski Could you respond, so we can close it?

**Comment by ggruszczynski** [comment]
I will, hopefully during the weekend/next week...

**Comment by ggruszczynski** [comment]
@TravisMitchell I added PhaseField_init as you requested. I have no idea what is in the `csf` folder, thus I moved the RT example to d2q9_pf_velocity.

**Comment by llaniewski** [comment]
@TravisMitchell go or no go?

**Pull request merged**
