### PR TITLE
Setting NVCC path in compilation

### PR DESCRIPTION
**Pull request by Raflen**
I modified the mechanism that sets the path to nvcc in CLB/config.mk

### CODE REVIEW

**Comment by mdzik** [comment]
Welcome in TCLB

We do not provide detection mechanism, so pleas add an option for nvcc path, and use $CUDA_HOME/bin  as reasonable default

What does "testsss" do?  :)

**Comment by Raflen** [comment]
Dear Sir,

all changes were done by Mr Ł. Łaniewski, we just used my laptop and my
github account. Please contact him with further ideas.

This folder is actually useless, it must have been added by accident. I
will delete it as soon as I figure out how to do this.

2016-10-25 14:15 GMT+02:00 mdzik <notifications@github.com>:

**Comment by mdzik** [comment]
No worries.
Just 
git rm file
git commit
git push

**Comment by mdzik** [comment]
@llaniewski  this is dead?

**Comment by llaniewski** [comment]
Will do in #124 in [V6.1 RC]

**Pull request closed without merging**
