### PR TITLE
XPath based modification

### PR DESCRIPTION
**Pull request by llaniewski**
# Description
I added support for adding small (and big) modifications to the xml which is being run on the command line.

## How it works
The syntax quite simple. For instance if you want to set the `output` attribute of your case, that would be:
```bash
CLB/d2q9/main file.xml @output = "test/"
```

Where `@output` can be any [XPath](https://en.wikipedia.org/wiki/XPath) expression matching some attributes. For instance:
```bash
CLB/d2q9/main file.xml //@output = "test/"
```
Would substitute `output` attribute with `test/` *everywhere* in the case file. With this you can do:
```bash
CLB/d2q9/main file.xml //@Viscosity = "0.16"
```
To run your case with a different Viscosity

## Notice
**The xml file (with all modification) is saved in the output directory with all the results for later inspection**

## Operators
I implemented three operators: `=`, `insert` and `print`. One can add new operators later on.

### `print` operator
Just prints what the XPath maches:
#### Examples
```bash
# print all Params attributes:
CLB/d2q9/main file.xml //Params/@* print
```

### `=` operator
Substitutes the matching attributes with `[xpath expression] = [value]` or add attribute to nodes with `[xpath expression] @[attribute name] = [value]`.
#### Examples
```bash
# change output path everywhere in the case file
CLB/d2q9/main file.xml //@output = "test/"
# change viscosity
CLB/d2q9/main file.xml //@Viscosity = "test/"
# change the length of domain
CLB/d2q9/main file.xml Geometry/@nx = "128"
# select field to export in VTK
CLB/d2q9/main file.xml //VTK/@what = "U,Rho"
# select field to export in VTK (even if the attribute didn't exist)
CLB/d2q9/main file.xml //VTK @what = "U,Rho"
```

### `insert` operator
Inserts an arbitrary piece of XML code into the case. You can specify where it should be placed with:

specifier | placement
--- | ---
`after` | after the selected node (sibling)
`before` | before the selected node (sibling)
`last` (default) | at the end of the selected node (child)
`first` | at the beginning of the selected node (child)

#### Examples
```bash
# run some more iterations at the end
CLB/d2q9/main file.xml . insert '<Solve Iterations="100"/>'
# add some parameters
CLB/d2q9/main file.xml Model insert '<Params Viscosity="10"/>'
# add a Log output
CLB/d2q9/main file.xml Model insert after '<Log Iterations="10"/>'
# add VTK output before every Solve
CLB/d2q9/main file.xml //Solve insert before '<VTK/>'
```

### `delete` operator
Deletes what the XPath maches.
#### Examples
```bash
# Delete all VTK output:
CLB/d2q9/main file.xml //VTK delete
```

### CODE REVIEW

**Comment by llaniewski** [comment]
@mdzik @TravisMitchell @ggruszczynski Any thoughts?

**Comment by llaniewski** [comment]
You can do even more complex things.

For an xml like:
```xml
...
 <Units>
  <Params D="0.01m" gauge="32"/>
  <Params Viscosity="1e-5m2/s" gauge="0.01"/>
 </Units>
...
```
one can modify the mesh density with:
```xml
CLB/d2q9/main file.xml Units/Params[@D]/@gauge = 64
```

**Comment by TravisMitchell** [comment]
I quite like the idea, it will be useful for grid convergence (or scaling) tests. Could potentially use it for parametric studies as well. Although would need to be slightly careful and be sure to rename the outputs as well each time.

**Comment by llaniewski** [comment]
> [...] Although would need to be slightly careful and be sure to rename the outputs as well each time. (@TravisMitchell )

Yes, this is related to #132 . But I don't really have a nice automatic way to generate the new name, for the output not to be overwritten.

We can opt for **never overwrite** strategy (generating new suffix, or directory every time the code is run), but this can be a bit tricky and I don't know if it's the way we want to go. We can move the discussion on that to #132

As for this PR, one can combine modification of parameters with modification of output directory:
```xml
CLB/d2q9/main case.xml //@Viscosity = 0.01 //@output = "output/low_visc/"
```

**Comment by TravisMitchell** [comment]
A possible addition to the capability of this could be to alter (i.e. find and replace) for node types. I came across this while playing around with the phase field velocity model that has both MRT and CM node types. For which having an inline switch between would have saved having two run files. From discussions with @llaniewski this could also be a useful feature for switching boundary conditions between runs.

**Pull request merged**
