### PR TITLE
Doxygen

### PR DESCRIPTION
**Pull request by ggruszczynski**
# Usage

Doxygen is able to generate documentation which provide some insight to the code structure.

## Install doxygen (Ubuntu 18.04)

You can download doxygen from the official website <http://www.doxygen.nl/index.html>.

Or install via command line:

```.sh
sudo apt-get update -y
sudo apt-get install -y doxygen
```

## Generate documentation

To generate the documentation run the following command from the main TCLB folder

```.sh
doxygen docs-by-doxygen/DoxygenConfig
```

## Read documentation

Next, open `docs-by-doxygen/doxygen/html/index.html` in your browser.

### CODE REVIEW

**Comment by llaniewski** [comment]
@ggruszczynski 
Does this work on the `src/` code, or the generated code in `CLB/model/` ?

There is existing (legacy) doxygen support with `make d2q9/doc`, which creates doxygen help for the generated code. Do you plan to merge these functionalities or you think we should drop the old one?

- The old doxygen config file: https://github.com/CFD-GO/TCLB/blob/master/src/conf.doxygen
- Relevant makefile line: https://github.com/CFD-GO/TCLB/blob/90f53ff40d16c677968abcf33723619919a6860a/src/makefile.main.Rt#L174

**Comment by llaniewski** [comment]
FYI: @trisbsamson @QuantumAlex

**Comment by llaniewski** [comment]
@ggruszczynski Can we get this out of the way? Please merge your idea with the current doxygen support (`make d2q9/doc`).

**Comment by ggruszczynski** [comment]
@llaniewski I will at it after the holidays.

**Comment by ggruszczynski** [comment]
@llaniewski I merged the stuff with the legacy doxygen and added Readme.
Shall be easier to discover for newcomers.

**Review by llaniewski — APPROVED** [review]

**Pull request merged**
