### PR TITLE
Move examples

### PR DESCRIPTION
**Pull request by mdzik**
I've moved examples. Basic structure is same as for models.
I hope that I figured out most of them, but A LOT of further clean-up is needed

### CODE REVIEW

**Comment by mdzik** [comment]
For #120

**Comment by llaniewski** [comment]
@shkodm, @wojtasMEiL, Please write if your examples are in right folders.

**Comment by shkodm** [comment]
Regarding  a186c67575a3b0d9c0cbbac1f7ac1839707f7f2e , maybe folder "geometry" would more appropriate, that "data" ?  "data" is ambiguous, in my opinion.

**Comment by mdzik** [comment]
maybe input_data or something? It might be something else than geometry (in general). I think sin.csv also should go there

**Comment by llaniewski** [comment]
@mdzik @shkodm data is good. Leave it. If no other comments, I will merge it after tests complete.

**Pull request merged**
