### PR TITLE
Cleaned d2q9s and a lot more ;) / 6.1 RC1 ?

### PR DESCRIPTION
**Pull request by mdzik**
Lots of d2q9 refactorization, python integration, merged changes from llaniewski
previous PR #108

### CODE REVIEW

**Comment by mdzik** [comment]
@llaniewski Do you have any idea why: https://travis-ci.org/mdzik/TCLB/jobs/181289315#L592 ??

The command "./configure --enable-double **--disable-cuda** --enable-marklines --enable-marklines --enable-coverage --with-python --enable-paranoid" exited with 0.

........
Handlers/acParams.o: In function `acParams::Init()':
**acParams.cpp:(.text+0x15ab): undefined reference to `cudaMemcpy'**
.....

**Comment by llaniewski** [comment]
Not so fast! work in progress :D

**Comment by mdzik** [comment]
It work on CPU, with test etc. So "only" mixed build has some progress.
I have working TravisCI VM, if you need more output you know where to find
me ;)

2016-12-05 16:59 GMT+01:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
Created separated branch for this version. Please merge all things related to the new version there. Closing this to clean up the mess.

**Pull request closed without merging**
