### PR TITLE
Templates for ISSUE/PULL REQUEST

### LINKED ISSUE #34: Merge policy
New rule proposal:
ANY new, model-related future/helper (auto BC, feq/collision helper etc.) will not be merged without reference to wiki (in code) OR at minimum meaningful API doc-string. Things like lib/boundary.R are unusable without that
 

Also, maybe we should come out with some merging guide, especially if we want someone to use it ;)

### PR DESCRIPTION
**Pull request by mdzik**
proposal to resolve #34

### CODE REVIEW

**Comment by mdzik** [comment]
There will be the day, that I won't forget to skip ci :p

**Comment by mdzik** [comment]
Maybe we should add some obligatory part, especially original reference?

**Comment by mdzik** [comment]
Merge??

**Comment by llaniewski** [comment]
After I pull requested to your repo, I saw How it works ... I think that what is written now, belongs in CONTRIBUTING.md and the pull request and issue templates, should be: templates. Something like:

Please fill in this template, so that we will know what to expect:
I added/modified a model _name of the model_ based on _paper_.
I added/modified _some nice name_ feature. Added XML element _name of the element_.

I will think on that and probably pull request you.

**Comment by mdzik** [comment]
Moved to another branch in source repo (@mdzik/github-files)

**Pull request closed without merging**
